# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Taelim's blog
google_analytics: taelim
title: Taelim's blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Taelim's blog

description: Taelim's blog
author:
  name: Taelim Hwang
  email: ghkdxofla@gmail.com
  github: ghkdxofla
  twitter: ghkdxofla
  pinterest: ghkdxofla
  linkedin: taelim-hwang-69135a149
  bio: Normal life
  email_md5: 71f7d3fe60f25347506c60bc7f631e7d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://images.pexels.com/photos/1137525/pexels-photo-1137525.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-admin
